name: Publish Package

on:
  workflow_call:
    inputs:
      scope:
        description: Scope for GitHub Package Registry
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
  npm-publish:

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js for npm
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Run npm ci
        run: npm ci
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
      - name: Setup Node.js for gpr
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: ${{ inputs.scope }}
      - name: Publish to gpr
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
