name: NPM Test

on:
  workflow_call:

jobs:
  npm-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node:
          - 16
          - 18
          - 20

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          check-latest: true
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test --if-present
